### ISSUE TITLE
bio run dev-daily error

### ISSUE THREAD

**Issue by wenlisu** [weidian-inc/bio-cli#1]
node -v
v9.0.0
npm -v
5.5.1
platform：MAC

![image](https://user-images.githubusercontent.com/16130875/37200389-9653173c-23bf-11e8-8826-6ab57458fbc0.png)

**Comment by wenlisu** [comment]
Because I don't have to install dependencies！！！

**Comment by hoperyy** [comment]
@wenlisu 

![image](https://user-images.githubusercontent.com/5757051/37236888-915e079a-2447-11e8-9dfe-7dfe9bb8995f.png)

The key "replace" is needed in "bio.config.js"

**Comment by wenlisu** [comment]
@hoperyy 
I'm sorry,So what should I do?

**Comment by hoperyy** [comment]
@wenlisu 只需要重新新建一个空目录，重新从 init 命令开始执行即可，重新初始化一个项目目录。

感觉可能是你之前不小心修改了 bio.config.js 的内容导致的问题。

我这边也没有做好错误提示哈，抱歉
